-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 15:50:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Image_repository
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Image_repository
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Image_repository` DEFAULT CHARACTER SET utf8 ;
USE `Image_repository` ;

-- -----------------------------------------------------
-- Table `Image_repository`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Image_repository`.`images` (
  `idimage` INT NOT NULL AUTO_INCREMENT,
  `imageName` VARCHAR(45) NULL,
  `imagePath` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Image_repository`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Image_repository`.`tags` (
  `idimage` INT NOT NULL,
  `tag` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idimage`, `tag`),
  CONSTRAINT `fk_tag_to_image`
    FOREIGN KEY (`idimage`)
    REFERENCES `Image_repository`.`images` (`idimage`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Image_repository`.`colours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Image_repository`.`colours` (
  `idimage` INT NOT NULL,
  `colourname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idimage`, `colourname`),
  CONSTRAINT `fk_colours_to_images`
    FOREIGN KEY (`idimage`)
    REFERENCES `Image_repository`.`images` (`idimage`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
